{{ if ne .Values.test true }}
apiVersion: v1
kind: Service
metadata:
  name: cloudant-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 31111
  selector:
    name: cloudant-deployment
{{ end }}
