{{ if and (ne .Release.IsInstall false) (ne .Values.test true) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cloudant-pv-claim
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
{{ end }}
